name: conectify_example
description: Ejemplo de uso del paquete conectify
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  conectify:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  coverage: ^1.7.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
